### ISSUE TITLE
Not working Sound with 0.97.9 SVN Version 37

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hugoruscitti/donceferino#3]
```
What steps will reproduce the problem?

+ Starting the SDL library: [OK]
+ Loading: /usr/share/ceferino/ima/fuente_2.png
Found 189 characters in bitmap
+ Loading images: .................. [OK]
+ Starting audio system:  [OK]
+ Loading sound files: ............. [ERROR]
Can't load 'T�@': Mix_LoadWAV_RW with NULL src
- Disabled sound system because of errors
+ Loading music files: .. [OK]
+ Loading intro: ...... [OK]
ALSA lib pcm.c:7897:(snd_pcm_recover) underrun occurred
+ Loading presentation:  [OK] 

What is the expected output? What do you see instead?

To have Sound working with 0.97.9 SVN Version 37.


What version of the product are you using? On what operating system?

I not can use Sound with 0.97.9 SVN Version 37

With older Version 0.97.8 works Sound.

This is with openSUSE. I make RPM for Don Ceferino Hazaña .

Please provide any additional information below.


```

Original issue reported on code.google.com by `nemysisbsd` on 24 Nov 2014 at 12:01

**Comment by perdigao1** [comment]
I am also getting the same error. I am running ceferino under ubuntu. I tried modifying OS sound settings. I should perhaps say that I also experience no sound with other games when I moved from Doudou linux to lubuntu.

**Comment by perdigao1** [comment]
I found the error after debugging and compiling under Codeblocks. The code is actually fine but g++ does not appear to compile the code properly. The problem occurs in audio.cc file, in void audio :: cargar_sonidos(void), at the for loop, line 144. The for loop is not testing the variable i<12 properly, because somehow value i overruns to i=12 and then creates the error. This appears to be a compilation error. A quick solution that works well is to replace it with value "12.0" and works fine.
